# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ffmpeg_manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QFileDialog
import ffmpeg_codec

selecr_dir = ""

class Ui_FFMpegAudioManager(object):
    def setupUi(self, FFMpegAudioManager):
        FFMpegAudioManager.setObjectName("FFMpegAudioManager")
        FFMpegAudioManager.resize(744, 436)
        self.btSelect = QtWidgets.QToolButton(FFMpegAudioManager)
        self.btSelect.setGeometry(QtCore.QRect(290, 150, 51, 31))
        self.btSelect.setObjectName("btSelect")
        self.title = QtWidgets.QLabel(FFMpegAudioManager)
        self.title.setGeometry(QtCore.QRect(100, 120, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.logText = QtWidgets.QPlainTextEdit(FFMpegAudioManager)
        self.logText.setGeometry(QtCore.QRect(380, 50, 321, 351))
        self.logText.setObjectName("logText")
        self.btStart = QtWidgets.QPushButton(FFMpegAudioManager)
        self.btStart.setGeometry(QtCore.QRect(100, 220, 101, 31))
        self.btStart.setObjectName("btStart")
        self.srcPath = QtWidgets.QLineEdit(FFMpegAudioManager)
        self.srcPath.setGeometry(QtCore.QRect(100, 150, 181, 31))
        self.srcPath.setObjectName("srcPath")

        self.retranslateUi(FFMpegAudioManager)
        QtCore.QMetaObject.connectSlotsByName(FFMpegAudioManager)

        def select_category():
            self.srcPath.clear()
            global selecr_dir
            selecr_dir = QFileDialog.getExistingDirectory(FFMpegAudioManager, "选择文件夹", os.getcwd())
            self.srcPath.setText(selecr_dir)

        self.btSelect.clicked.connect(select_category)

        def start():
            ffmpeg_codec.start_work(selecr_dir, self.logText)

        self.btStart.clicked.connect(start)

    def retranslateUi(self, FFMpegAudioManager):
        _translate = QtCore.QCoreApplication.translate
        FFMpegAudioManager.setWindowTitle(_translate("FFMpegAudioManager", "Form"))
        self.btSelect.setText(_translate("FFMpegAudioManager", "..."))
        self.title.setText(_translate("FFMpegAudioManager", "选择文件夹"))
        self.btStart.setText(_translate("FFMpegAudioManager", "开始"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FFMpegAudioManager = QtWidgets.QWidget()
    ui = Ui_FFMpegAudioManager()
    ui.setupUi(FFMpegAudioManager)
    FFMpegAudioManager.show()
    sys.exit(app.exec_())
